www/config/routes.rb
MeagarNet::Application.routes.draw do

  root :to => "updates#index"

	match 'login'  => 'user_sessions#new', :via => 'get'
	match 'login'  => 'user_sessions#create', :via => 'post'
	match 'logout' => 'user_sessions#destroy'

	match 'resume'  => 'static#resume'
	match 'contact' => 'static#contact'

	resources 'updates'

	resources 'designs' do
		member do
			get :move
		end
	end

	resources 'projects' do
		member do 
			get :move
		end

		resources 'files', :controller => 'Project_files' do
			member do
				get :save
				get :move
			end
		end
	end

end

www/app/models/project.rb
class Project < ActiveRecord::Base

  has_many :files, :class_name => 'Project_file', :order => 'position'

  acts_as_list

	has_attached_file :icon, :styles => { :normal => '540x200>' }, :default_style => :normal

	validates_length_of :name, :within => 1..50
	validates_presence_of :brief
	validates_presence_of :description

end

www/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def nav
    'projects'
  end

  # GET /projects
  def index
    @projects = Project.all(:order => 'position')
  end

  # GET /projects/1
  def show
    if params[:id].to_i != 0
      @project = Project.find(params[:id])
    else
      @project = Project.find_by_name(params[:id].sub('_', ' '))
    end

    @title = ['Projects', @project.name]
  end


  #
  # Admin actions
  #
  
  require_user :new, :create, :destroy, :update, :edit, :move

  def move
    @project = Project.find(params[:id])
    m = @project.method('move_' + params[:direction])
    m.call()
    redirect_to projects_path
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  def create
    @project = Project.new(params[:project])

    if @project.save
      flash[:notice] = 'Project was successfully created.'
      redirect_to(@project)
    else
      render :action => "new"
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      flash[:notice] = 'Project was successfully updated.'
      redirect_to(@project)
    else
      render :action => "edit"
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to(projects_url)
  end
end

www/app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
	<p class="name">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p class="brief">
		<%= f.label :brief %>
		<%= f.text_field :brief %>
	</p>

	<p class="description">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :icon %>
		<%= f.file_field :icon %>
	</p>

	<p class="actions">
		<%= f.submit %>
	</p>
<% end %>

www/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

www/app/views/projects/index.html.erb
<%= trail 'Projects' %>

<p>
Below are various projects I've polished to the point where they can be presented online.
Additional projects will appear here after some additional testing and cleanup.
</p>

<ul class="projects">
  <% for p in @projects %>
    <li class="project" style="background-image:url('<%= p.icon.url %>')">
      <h3><a href="<%= project_path(p) %>"><%= p.name %></a></h3>
      <%= markdown p.brief %>
      <%= p.files.count %> file(s)
      <%= admin_opts do %>
        <%= admin_link 'Edit', edit_project_path(p) %>
        <%= admin_link 'Delete', p, :confirm => 'Are you sure?', :method => :delete %>
        <%= move_links(p) %>
      <% end %>
    </li>
  <% end %>
  
  <%= admin_only do %>
    <%= link_to 'New project', new_project_path %>
  <% end %>

</ul><!-- Projects -->

www/app/views/projects/new.html.erb
<h1>New project</h1>

<% form_for @project, :html => { 'multipart' => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => { :f => f }  %> 
  <p><%= f.submit 'Create' %></p>
<% end %>

<%= back_to projects_path %>

www/app/views/projects/show.html.erb
<%= trail ['Projects', projects_path], @project.name %>

<%= image_tag @project.icon.url %>

<h2><%= @project.name %></h2>

<div class="description">
	<%= markdown @project.description %>
</div>

<div class="files">
	<table>
		<tr>
			<%= admin_only do %><th></th><% end %>
			<th class="filename">Filename</th>
			<th class="description">Description</th>
			<th class="createdAt">Uploaded At</th>
			<th class="size">Size (KB)</th>
			<th></th>
		</tr>

		<% for f in @project.files -%>
			<tr class="<%= cycle 'odd', 'even' %> <%= f.content_type.split('/').join('-') %>">
				<%= admin_only do -%>
					<td class="admin-opts">
						<%= admin_link 'Edit', edit_project_file_path(@project, f) %>
						<%= admin_link 'Delete', project_file_path(@project, f) %>
						<%= admin_link 'Top',    move_project_file_path(@project, f, :direction => :to_top) %>
						<%= admin_link 'Higher', move_project_file_path(@project, f, :direction => :higher) %>
						<%= admin_link 'Lower',  move_project_file_path(@project, f, :direction => :lower) %>
						<%= admin_link 'Bottom', move_project_file_path(@project, f, :direction => :to_bottom) %>
					</td>
				<% end -%>
				<td class="filename"><%= link_to f.filename, project_file_path(@project, f) %></td>
				<td class="description"><%= markdown f.description %></td>
				<td class="createdAt"><%= f.created_at.to_s(:short) %></td>
				<td class="size"><%= file_size(f.size) %></td>
				<td class="save"><%= link_to span(f.filename), save_project_file_path(f), :title => "Download #{f.filename}" %></td>
			</tr>
		<% end %>

	</table>
</div>

<%= admin_only do -%>
	<%= link_to 'Edit', edit_project_path(@project) -%> |
	<%= link_to 'Add File', new_project_file_path(@project.id) -%>
<% end -%>

<%= back_to projects_path -%>