www/config/routes.rb
MeagarNet::Application.routes.draw do

  root :to => "updates#index"

	match 'login'  => 'user_sessions#new', :via => 'get'
	match 'login'  => 'user_sessions#create', :via => 'post'
	match 'logout' => 'user_sessions#destroy'

	match 'resume'  => 'static#resume'
	match 'contact' => 'static#contact'

	resources 'updates'

	resources 'designs' do
		member do
			get :move
		end
	end

	resources 'projects' do
		member do 
			get :move
		end

		resources 'files', :controller => 'Project_files' do
			member do
				get :save
				get :move
			end
		end
	end

end

www/app/models/design.rb
class Design < ActiveRecord::Base

	has_attached_file :photo, :styles => { :normal => '540x200>' }, :default_style => :normal

  acts_as_list

end

www/app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  def initialize
		super
    @title = ["Web Designs"]
  end

  def nav
    'designs'
  end

  # GET /designs
  def index
    @designs = Design.all(:order => 'position')
  end

  # GET /designs/1
  def show
    @design = Design.find(params[:id])
    @title << @design.title
  end

  #
  # Admin actions
  #

  require_user :new, :create, :destroy, :edit, :update, :move

  def move
    @design = Design.find(params[:id])
    m = @design.method('move_' + params[:direction])
    m.call()
    redirect_to :action => :index
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
    @design = Design.find(params[:id])
  end

  # POST /designs
  def create
    @design = Design.new(params[:design])

    if @design.save
      flash[:notice] = 'Design was successfully created.'
      redirect_to(@design)
    else
      render :action => "new"
    end
  end

  # PUT /designs/1
  def update
    @design = Design.find(params[:id])

    if @design.update_attributes(params[:design])
      flash[:notice] = 'Design was successfully updated.'
      redirect_to(@design)
    else
      render :action => "edit"
    end
  end

  # DELETE /designs/1
  def destroy
    @design = Design.find(params[:id])
    @design.destroy

    redirect_to(designs_url)
  end

end

www/app/helpers/designs_helper.rb
module DesignsHelper

  def thumbnail(design, url)
    ('<div class="thumbnail"><a title="' + design.title + '" class="thumbnail" href="' +
			url +  '" style="background-image:url(' + design.photo.url +
			')"><span>' + design.title + '</span></a></div>').html_safe
  end

end

www/app/views/designs/_form.html.erb
<% table_form(f) do |t| %>
  <%= t.text_field :title %>
  <%= t.text_field :address %>
  <%= t.file_field :uploaded_data %>
  <%= t.text_area :description %>
<% end %>

www/app/views/designs/edit.html.erb
<h1>Editing design</h1>

<% form_for @design, :html => { 'multipart' => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p><%= f.submit 'Update' %></p>
<% end %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

www/app/views/designs/index.html.erb
<%= trail 'Web Design' %>

<p>
I've worked as a web designer for more than a decade.  My tools have evolved
over the years from Microsoft FrontPage in the mid 90's to the open-source,
Linux environment I use today.
</p>

<p>
Below are some of the sites I've worked on, many of which I still maintain
and several of which I host on my Linux-based web server.
</p>

<% i = 0 %>
<table class="designs">
  <tr>
  <% for d in @designs %>
    <td><div class="design"><%= thumbnail(d, design_path(d)) %></div>
      <%= admin_opts do %>
        <%= admin_link 'Edit', edit_design_path(d) %>
				<%= admin_link 'Delete', d, :confirm => 'Are you sure?', :method => :delete %>
				<%= move_links(d) %>
      <% end -%>
    </td>
    <%= cycle('', '', '</tr><tr>'.html_safe) -%>
  <% end %>
  </tr>
</table>

<%= admin_only do %>
  <%= link_to 'New design', new_design_path %>
<% end %>

www/app/views/designs/new.html.erb
<h1>New design</h1>

<% form_for @design, :html => { 'multipart' => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => { :f => f } %>
    <p> <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', designs_path %>

www/app/views/designs/show.html.erb
<%= trail ['Web Design', designs_path], @design.title %>

<div class="design">

  <div style="float:right">
    <%= thumbnail(@design, @design.address) %>
  </div>

  <p>
  <h2><%=h @design.title %></h2>
  </p>

  <p>
    <%= link_to @design.address, @design.address %>
  </p>

  <%= markdown @design.description %>

</div>

<%= back_to designs_path %>