www/config/routes.rb
MeagarNet::Application.routes.draw do

  root :to => "updates#index"

	match 'login'  => 'user_sessions#new', :via => 'get'
	match 'login'  => 'user_sessions#create', :via => 'post'
	match 'logout' => 'user_sessions#destroy'

	match 'resume'  => 'static#resume'
	match 'contact' => 'static#contact'

	resources 'updates'

	resources 'designs' do
		member do
			get :move
		end
	end

	resources 'projects' do
		member do 
			get :move
		end

		resources 'files', :controller => 'Project_files' do
			member do
				get :save
				get :move
			end
		end
	end

end

www/app/models/update.rb
class Update < ActiveRecord::Base
end

www/app/controllers/updates_controller.rb
class UpdatesController < ApplicationController

  # GET /updates
  def index
    @updates = Update.all(:order => 'created_at DESC')
  end

  # GET /updates/1
  def show
    @update = Update.find(params[:id])
  end

  #
  # Admin actions
  #
  
  require_user :new, :create, :destroy, :edit, :update

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
    @update = Update.find(params[:id])
  end

  # POST /updates
  def create
    @update = Update.new(params[:update])

    if @update.save
      flash[:notice] = 'Update was successfully created.'
      redirect_to(@update)
    else
      render :action => "new"
    end
  end

  # PUT /updates/1
  def update
    @update = Update.find(params[:id])

    if @update.update_attributes(params[:update])
      flash[:notice] = 'Update was successfully updated.'
      redirect_to(@update)
    else
      render :action => "edit"
    end
  end

  # DELETE /updates/1
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    redirect_to(updates_url)
  end
end

www/app/helpers/updates_helper.rb
module UpdatesHelper
end

www/app/views/updates/edit.html.erb
<h1>Editing update</h1>

<% form_for(@update) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

www/app/views/updates/index.html.erb
<%= controller.nav %>

<div class="welcome">
  <h2><span>Welcome to meagar.net</span></h2>

  <p>
  Welcome to my online portfolio.  This site showcases some of my work in the IT
  field from the past several years, including software I've written (most of it
  <em>not</em> professionally, as that code remains property of my previous
  employers) and several websites I've designed.
  </p>

	<a style="display:block; width:289px; height:121px; margin:0 auto"
			href="http://www.conquercancer.ca/site/TR?px=2603458&amp;pg=personal&amp;fr_id=1361&amp;s_src=BF_emailbadge2011">
    <img alt="Progress Meter" src="http://badge.boundlessfundraising.com/en_CA/image/display/cfrccca/1361/2603458" />
  </a>

</div><!-- .welcome -->

<ul class="updates">
	<% for u in @updates %>
		<li class="update">
			<h3><%= u.subject %></h3>
			<span class="date">Posted <%= u.created_at.to_s(:short) %></span>
			<div class="body">
				<%= markdown(u.body) %>
			</div><!-- .body -->
			<%= admin_opts do %>
				<%= admin_link 'Edit', edit_update_path(u) %>
				<%= admin_link 'Delete', u, :confirm => 'Are you sure?', :method => :delete %>
			<% end %>

		</li><!-- Update -->
	<% end %>

	<% admin_only do %>
		<%= link_to 'New update', new_update_path %>
	<% end %>

</ul><!-- .updates -->

<div class="updatenav">

</div>

www/app/views/updates/new.html.erb
<h1>New update</h1>

<% form_for(@update) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', updates_path %>

www/app/views/updates/show.html.erb
<p>
  <b>Subject:</b>
  <%=h @update.subject %>
</p>

<p>
  <b>Body:</b>
  <%=h @update.body %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>