www/config/routes.rb
MeagarNet::Application.routes.draw do

  root :to => "updates#index"

	match 'login'  => 'user_sessions#new', :via => 'get'
	match 'login'  => 'user_sessions#create', :via => 'post'
	match 'logout' => 'user_sessions#destroy'

	match 'resume'  => 'static#resume'
	match 'contact' => 'static#contact'

	resources 'updates'

	resources 'designs' do
		member do
			get :move
		end
	end

	resources 'projects' do
		member do 
			get :move
		end

		resources 'files', :controller => 'Project_files' do
			member do
				get :save
				get :move
			end
		end
	end

end

www/app/models/project_file.rb
class Project_file < ActiveRecord::Base

  belongs_to :project

	has_attached_file :attachment

	validates_presence_of :description


#  has_attachment :storage => :file_system,
#    :max_size => 5.megabytes

#  validates_as_attachment

  acts_as_list

  def auto_content_type
    self.content_type
  end

  def auto_content_type=(value)
    self.content_type = value unless value == 'Automatic'
  end

  def source_type
    if self.content_type =~ /^source*/
      return self.content_type.sub('source/', '');
    end
  end

  def mime_type
    if self.content_type =~/^source*/
      return "text/plain"
    end
    self.content_type
  end

	def content_type
		self.attachment_content_type
	end

	def url
		self.attachment.url
	end

	def filename
		self.attachment.original_filename
	end

	def path
		self.attachment.path
	end

	def size
		self.attachment_file_size
	end

end

www/app/controllers/project_files_controller.rb
class ProjectFilesController < ApplicationController
  
  #caches_page :show

  def nav
    'projects'
  end

  # GET /files/1
  def show
    @file = Project_file.find(params[:id])
    @title = [@file.project.name, @file.filename]

    if @file.content_type =~ /^image*/
      render :action => 'show_image'
    elsif @file.content_type =~ /^source*/ or @file.content_type =~ /^text*/
      render :action => 'show_source'
    elsif @file.content_type =~ /^application*/
      redirect_to :action => 'save', :id => @file
    end
  end

  # GET /files/save/1
  def save
    @file = Project_file.find(params[:id])
    send_file("public/#{@file.url}", :filename => @file.filename, :type => @file.mime_type)
  end

  #
  # Admin actions
  #

  require_user :new, :create, :destroy, :edit, :update, :move
 
  def move
    @file = Project_file.find(params[:id])
    m = @file.method('move_' + params[:direction])
    m.call()
    redirect_to @file.project
  end

  # GET /files/new
  def new
    @file = Project_file.new
    @project = Project.find(params[:project_id])
  end

  # GET /files/1/edit
  def edit
    @file = Project_file.find(params[:id])
  end

  def update
    @file = Project_file.find(params[:id])
    if @file.update_attributes(params[:project_file])
      expire(@file)
      flash[:notice] = 'Project_file was successfully updated'
      redirect_to (@file.project)
    else
      render :action => 'edit'
    end
  end

  # POST /files
  def create
    @file = Project_file.new params[:project_file]
    @project = Project.find(params[:project_id])
    @file.project_id = @project.id

    if @file.save
      flash[:notice] = 'Project_file was successfully created.'
      redirect_to project_url(@project)
    else
      render :action => "new"
    end
  end

  # DELETE /files/1
  def destroy
    @file = Project_file.find(params[:id])
    @project = @file.project
    if @file
      expire(@file)
      @file.destroy
      redirect_to @project
    end
  end

  private

  def expire(file)
    # doesn't seem to play well with nested routes, using 
    # expire_page(:controller => 'file', :action => 'show', :id => ...)
    # tries to delete /files/show/id.htm instead of
    # /projects/project_id/files/file_id
    expire_page("/projects/#{@file.project_id}/files/#{@file.id}.html");
  end

end

www/app/helpers/project_files_helper.rb
require 'simplabs/highlight'

module ProjectFilesHelper

	def hilite_code(type, string)
		Simplabs::Highlight.highlight(type, string).html_safe
	end

end

www/app/views/project_files/_form.html.erb
<%= form_for [@project, @file], :html => { :multipart => true } do |f| %>
	<%= f.error_messages %>

	<p class="description">
		<%= f.label :description %>
		<%= f.text_field :description %>
	<p>

	<p>
		<%= f.label :attachment %>
		<%= f.file_field :attachment %>
	</p>

	<p>
	<%= f.label :auto_content_type, 'Content Type' %>
  <%= f.select :auto_content_type,
    { 'Automatic'   => 'Automatic',
      'C++ Source'  => 'source/cpp',
      'ASP Source'  => 'source/asp',
      'C Source'    => 'source/c',
      'Ruby Source' => 'source/rb',
      'Zip Archive' => 'application/zip' } %>

	<p class="action">
		<%= f.submit %>
	</p>

<% end %>

www/app/views/project_files/edit.html.erb
<h1>Editing attachment</h1>

<% form_for [@project, @attachment ], :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <p><%= f.submit 'Update' %></p>
<% end %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

www/app/views/project_files/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New attachment', new_attachment_path %>

www/app/views/project_files/new.html.erb
<h2>Add file to <%= @project.name %></h2>

<%= render 'form' %>

<%= link_to 'Back', @project %>

www/app/views/project_files/show_image.html.erb
<%= trail ['Projects', projects_path], [@attachment.project.name, project_path(@attachment.project)], @attachment.filename %>

<div style="text-align:center">
  <%= markdown @attachment.description %>
  <%= image_tag @attachment.public_filename, :class => 'Attachment' %>
</div>

www/app/views/project_files/show_source.html.erb
<%= trail ['Projects', projects_path], [@file.project.name, project_path(@file.project)], @file.filename %>

<%
  lineNo = 0
  f = File.new(@file.path)
	type = :c

	if @file.url.ends_with? '.asp'
		type = :asp
	elsif @file.url.ends_with? '.cpp'
		type = :cpp
	end

  lines = hilite_code(type, f.read()).split("\n");
-%>

<div class="Info">
  <h3><%= @file.filename %></h3>
  <%= back_to project_path(@file.project) %>
  <%= link_to span('Download'), save_project_file_path(@file), :class => 'download' %>
</div>


<div class="file">
  <table class="nums">
    <% lines.each do %>
      <tr class="<%= cycle 'odd', 'even' %>"><th><%= lineNo += 1 %></th></tr>
    <% end %>
  </table>
  <% reset_cycle %>

  <table class="lines">
    <% lines.each do |line| %>
      <tr class="<%= cycle 'odd', 'even' %>">
        <td><%= line.chomp.html_safe %> </td>
      </tr>
    <% end %>
  </table>
</div>